name: Feature
description: 기능
title: "feat: TITLE"
labels: ["feature"]
body:
  - type: textarea
    id: 상세
    attributes:
      label: Description
      description: 구현할 기능의 간단한 설명을 적어주세요.
    validations:
      required: true
